version: "3.9"

services:
  db:
    image: postgres:15
    container_name: task-manager-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: yourpassword
      POSTGRES_DB: postgres
    ports:
      - "5433:5432"
    networks:
      - task-manager-network
    restart: unless-stopped

  app:
    image: task-manager-app
    container_name: task-manager-app
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: yourpassword
    ports:
      - "8081:8081"
    networks:
      - task-manager-network
    restart: unless-stopped

networks:
  task-manager-network:
    driver: bridge